apiVersion: sparkoperator.k8s.io/v1beta2
kind: ScheduledSparkApplication
metadata:
  name: helloworld-scala-scheduled
  namespace: default
spec:
  schedule: "@every 1m"
  concurrencyPolicy: Forbid
  template:
    type: Scala
    mode: cluster
    image: rajendar38/spark-helloworld-scala:latest   # Use valid Spark 4.0.0 image
    imagePullPolicy: IfNotPresent
    mainClass: com.example.HelloWorld
    mainApplicationFile: local:///opt/spark/examples/jars/helloworld-scala.jar
    sparkVersion: 4.0.0
    restartPolicy:
      type: Never
    driver:
      cores: 1
      memory: 512m
      serviceAccount: spark-operator-spark
    executor:
      instances: 1
      cores: 1
      memory: 512m

